import { NAV_LINKS } from "./navLinks";
import { CATEGORY_IDS } from "./categoryIds";
import {
  PRIVACY_FOOTER_LINKS,
  ABOUT_US_FOOTER_LINKS,
  INFO_FOOTER_LINKS,
  SERVICES_FOOTER_LINKS,
} from "./footerLinks";

export {
  NAV_LINKS,
  CATEGORY_IDS,
  PRIVACY_FOOTER_LINKS,
  ABOUT_US_FOOTER_LINKS,
  INFO_FOOTER_LINKS,
  SERVICES_FOOTER_LINKS,
};
